name: Build, Test & Lint process runner
on:
  pull_request:
    types: [opened, synchronize]
    branches: [master, main, truck]

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JUSTO_REGISTRY_TOKEN }}
      - name: Build project
        run: npm run build --if-present
      - name: Run all tests
        run: npm test
      - name: Run lint
        run: npm run lint
